In [2]:
import pandas as pd

# Working with json

In [4]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [5]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-17,1789603201,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-17,1789603201,0.0382
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-17,1789603201,0.6750
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-17,1789603201,0.8290
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-17,1789603201,3.7900
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-17,1789603201,2.4700
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-17,1789603201,0.1700
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-17,1789603201,0.2040
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-17,1789603201,0.2780
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-17,1789603201,0.2780

# Working with SQL

In [8]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     - -------------------------------------- 0.5/11.9 MB 1.3 MB/s eta 0:00:09
     ---- ----------------------------------- 1.3/11.9 MB 2.6 MB/s eta 0:00:05
     ----- ---------------------------------- 1.6/11.9 MB 2.2 MB/s eta 0:00:05
     ------- -------------------------------- 2.1/11.9 MB 2.3 MB/s eta 0:00:05
     ------- -------------------------------- 2.4/11.9 MB 2.2 MB/s eta 0:00:05
     --------- ------------------------------ 2.9/11.9 MB 2.2 MB/s eta 0:00:05
     ---------- ----------------------------- 3.1/11.9 MB 2.2 MB/s eta 0:00:04
     ------------ --------------------------- 3.7/11.9 MB 2.1 MB/s eta 0:00:04
     -------------- ------------------------- 4.2/11.9 MB 2.2 MB/s eta 0:00:04
     --------------- ------------------------ 4.7/11.9 MB 2.2 MB/s eta 0:00:04
     ----------------- ---------------------- 5.2/11.9 MB 2.2 MB/s eta 0:00:03
     ------------------- -------------------- 5.8/11.9 MB 2.2 MB/s eta 0:00:03
     -------------------- ------------------- 6.0/11.9 MB 2.2 MB/s eta 0:00:03
     ---------------------- ----------------- 6.6/11.9 MB 2.2 MB/s eta 0:00:03
     ----------------------- ---------------- 6.8/11.9 MB 2.1 MB/s eta 0:00:03
     ------------------------ --------------- 7.3/11.9 MB 2.1 MB/s eta 0:00:03
     ------------------------ --------------- 7.3/11.9 MB 2.1 MB/s eta 0:00:03
     --------------------------- ------------ 8.1/11.9 MB 2.1 MB/s eta 0:00:02
     ---------------------------- ----------- 8.4/11.9 MB 2.1 MB/s eta 0:00:02
     ------------------------------ --------- 8.9/11.9 MB 2.1 MB/s eta 0:00:02
     -------------------------------- ------- 9.7/11.9 MB 2.2 MB/s eta 0:00:01
     ---------------------------------- ----- 10.2/11.9 MB 2.2 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 2.2 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 2.2 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 2.3 MB/s  0:00:05
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp314-cp314-win_amd64.whl size=248716 sha256=3c55418a039c26d8fe75c6d419f9e52ba9ab39a384aff3ef561f360b3678bdff
  Stored in directory: c:\users\nihal\appdata\local\pip\cache\wheels\a2\5a\60\e03682d488f501428666827b000cfa0da00163afcd74ce2c14
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002EEA5763B10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/28/04/e40098f3730e75bbe36a338926f566ea803550a34fb50535499f4fc4787a/mysql-connector-2.2.9.tar.gz
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002EEA5763C50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/28/04/e40098f3730e75bbe36a338926f566ea803550a34fb50535499f4fc4787a/mysql-connector-2.2.9.tar.gz

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import mysql.connector

In [12]:
conn=mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [18]:
df=pd.read_sql_query("SELECT*FROM CITY WHERE CountryCode LIKE 'USA'",conn)

C:\Users\Nihal\AppData\Local\Temp\ipykernel_16840\38655466.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("SELECT*FROM CITY WHERE CountryCode LIKE 'USA'",conn)

In [19]:
df

       ID          Name CountryCode        District  Population
0    3793      New York         USA        New York     8008278
1    3794   Los Angeles         USA      California     3694820
2    3795       Chicago         USA        Illinois     2896016
3    3796       Houston         USA           Texas     1953631
4    3797  Philadelphia         USA    Pennsylvania     1517550
..    ...           ...         ...             ...         ...
269  4062       Kenosha         USA       Wisconsin       89447
270  4063         Elgin         USA        Illinois       89408
271  4064        Odessa         USA           Texas       89293
272  4065        Carson         USA      California       89089
273  4066    Charleston         USA  South Carolina       89063

[274 rows x 5 columns]